### ISSUE TITLE
RFE: Update the test matrix for aiosmtpd

### ISSUE THREAD

**Issue by maxking** [aio-libs/aiosmtpd#316]
We should probably update the supported OSes and Python versions in the CI. Here is what I propose:

* Bump Ubuntu to 22.10 (latest version) and drop other one.
* Bump macOS to 12 (13 _just_ came out, so we can possibly bump to that after a while?)
* Drop support for Python 3.6 and pypy3.6
* Add support for Pypy3.7-3.9

With addition of 3.11 (see #314) this would make the test matrix *huge* though with 5 CPythons and 3 Pypy and 3 OSes (8x3=24 runs, not including LGTM and Qa) 😄 

Depending on what folks think, we _could_ limit to using only 1 ubuntu version (as representation for Linux) and maybe not run _every_ python on _every_ OS. Although, Idk how much customization does GHA matrix declarations support to even do that.

**Comment by maxking** [comment]
Although, 3.7 goes to EOL in 5mo, so we can drop 2 python versions, pypy3.7 and py37 soon.

**Comment by waynew** [comment]
Well, I'm pretty OK with the matrix - our tests are fast and generally speaking my goal with aiosmtpd is for it to be effectively "complete" at some point. Like... we should support RFC compliance and some hooks to make it easier on folks to consume, but aside from that there should be a point where we've basically squashed all the bugs and we're just making sure bit rot doesn't set in.

**Comment by waynew** [comment]
To be specific, *I'm OK with updating to the more comprehensive/24 run matrix*

I think we should update as part of the work for v1.5. I'm going through some of the issues/PRs and trying to put together as much of a picture of the work we need to get done for v1.5 :+1: and this is on the list

**Comment by pepoluan** [comment]
Sorry did not see this earlier.

> Bump Ubuntu to 22.10 (latest version) and drop other one.

Done

> Bump macOS to 12 (13 just came out, so we can possibly bump to that after a while?)

Ah, I'll go into the expand-ghci branch again and add 12.

> Drop support for Python 3.6

Done

> and pypy3.6

Partially

> Add support for Pypy3.7-3.9

TBH I only see 3.8 and 3.9 in PyPy.org

So I just added 3.8.

IIRC there are some things that still hasn't make it to 3.9, so maybe early 2023.

Besides been having coverage warnings with PyPy3.8 so I'd like to see what's messing up there first.

**Comment by pepoluan** [comment]
Okay, final version:

```yaml
      matrix:
        os: [ "macos-11", "macos-12", "ubuntu-18.04", "ubuntu-20.04", "ubuntu-22.04", "windows-latest" ]
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.6", "pypy3.7", "pypy3.8" ]
        exclude:
          - os: windows-latest
            python-version: pypy3.6
          - os: macos-11
            python-version: pypy3.6
          - os: macos-12
            python-version: pypy3.6
```

With special handling to skip coverage for pypy3.8
