### ISSUE TITLE
Bug: When I'm using docker-compose, After I put smtp service under the traefik, and I'm using the `proxyProtocol`, The connection will breke 

### ISSUE THREAD

**Issue by yingshaoxo** [aio-libs/aiosmtpd#372]
Here is the traefik code:
```
tcp:
  routers:
    smtp_router:
      entryPoints:
        - smtp
      rule: "HostSNI(`*`)"
      service: smtp_service
  services:
    smtp_service:
      loadBalancer:
        servers:
          - address: weloveparty_account_auth_service:25
        proxyProtocol:
          version: 2
        terminationDelay: 200
```

https://traefik.io/blog/announcing-traefik-2-4/#:~:text=However%2C%20when%20forwarding-,SMTP%20connections,-to%20a%20service
